### ISSUE TITLE
Sources bloat

### ISSUE THREAD

**Issue by gynther** [Asmor/5e-spellbook#1]
Several of the sources in the spellbook are redundant (Player's D&D Basic Rules and Hoard of the Dragon Queen Online Supplement) where the original PHB already contains the spells. Some sources are lesser known or (to my knowledge) not official material (Urban Arcana and En5ider)

My suggestion is that these non-standard sources are not to be picked as default to avoid clutter when looking through spells for most users.

**Comment by Asmor** [comment]
It now remembers when you filter out sources between page views
